apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-service-config
  namespace: amazon
data:
  SPRING_APPLICATION_NAME: shipping-service

  SPRING_DATASOURCE_URL: jdbc:postgresql://shipping-postgres:5432/amazondb-shipments
  SPRING_DATASOURCE_USERNAME: postgres

  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest

  FEIGN_ORDER_SERVICE_URL: http://order-service:8080

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
  MANAGEMENT_METRICS_TAGS_APPLICATION: shipping-service
