apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: amazon
type: Opaque
stringData:
  JWT_SECRET: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
  jwt-secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=