apiVersion: v1
kind: Secret
metadata:
  name: order-postgres-secret
  namespace: amazon
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: YW1hem9uZGItb3JkZXJz
