spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:postgresql://postgres:5432/amazondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cassandra:
    contact-points: cassandra
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: amazonks
    schema-action: CREATE_IF_NOT_EXISTS
  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin
  data:
    mongodb:
      uri: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin
    redis:
      host: redis
      port: 6379
      password: redispass
  
  port: 8080
jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration: ${JWT_EXPIRATION_MS:86400000}