apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-configmap
  namespace: amazon
data:
  SPRING_APPLICATION_NAME: product-service

  SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/amazondb-products
  SPRING_DATASOURCE_USERNAME: postgres

  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest

  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"

  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200

  FEIGN_ORDER_SERVICE_URL: http://order-service:8080
  FEIGN_USER_SERVICE_URL: http://user-service:8080

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus,health,info