{
 "title": "Order Service Dashboard",
 "refresh": "10s",
 "panels": [
  {
   "title": "Order Service HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"order-service\"}[1m]))",
     "legendFormat": "requests/sec"
    }
   ]
  },
  {
   "title": "Order Service Average Response Time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"order-service\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"order-service\"}[1m]))",
     "legendFormat": "avg response time"
    }
   ]
  },
  {
   "title": "Order Service JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"order-service\"})",
     "legendFormat": "memory used"
    }
   ]
  }
 ]
}