apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: amazon
  labels:
    app: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: billing-service-configmap
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: SPRING_DATA_REDIS_PASSWORD
              value: redispass
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
                  optional: true