apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: amazon
  labels:
    app: billing-service
spec:
  type: ClusterIP
  selector:
    app: billing-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080