apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: amazon
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/amazondb-users
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  FEIGN_ORDER_SERVICE_URL: http://order-service:8080
  FEIGN_BILLING_SERVICE_URL: http://billing-service:8080
  LOKI_URL: http://loki:3100/loki/api/v1/push
