apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-service-config
  namespace: amazon
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://billing-postgres:5432/amazondb-billing
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin