apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: billing-postgres
  namespace: amazon
spec:
  serviceName: billing-postgres
  replicas: 1
  selector:
    matchLabels:
      app: billing-postgres
  template:
    metadata:
      labels:
        app: billing-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: billing-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: billing-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: billing-postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: billing-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: billing-postgres-storage
          persistentVolumeClaim:
            claimName: billing-postgres-pvc