apiVersion: v1
kind: Secret
metadata:
  name: billing-postgres-secret
  namespace: amazon
type: Opaque
stringData:
  POSTGRES_DB: amazondb-billing
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres