spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/amazondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin
  data:
    redis:
      host: redis
      port: 6379
      password: redispass
  neo4j:
    uri: bolt://neo4j:7687
    username: neo4j
    password: neo4jpass
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration: ${JWT_EXPIRATION_MS:86400000}
cache:
    type: redis
    redis:
      time-to-live: 300000   