spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/amazondb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration: ${JWT_EXPIRATION_MS:86400000}