spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://postgres:5432/amazondb
    username: postgres
    password: postgres
  data:
    redis:
      host: amazon-redis
      port: 6379
      password: redispass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mongodb:
    uri: mongodb://root:rootpass@mongo:27017/amazonmongo?authSource=admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
  expiration: ${JWT_EXPIRATION_MS:86400000}

feign:
  order-service:
    url: http://order-service:8080
  user-service:
    url: http://user-service:8080