global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets: ['user-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: product-service
    static_configs:
      - targets: ['product-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: order-service
    static_configs:
      - targets: ['order-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: shipping-service
    static_configs:
      - targets: ['shipping-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: billing-service
    static_configs:
      - targets: ['billing-service:8080']
    metrics_path: /actuator/prometheus
