apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: order-service-configmap
            - secretRef:
                name: order-postgres-secret
          env:
            - name: SPRING_NEO4J_URI
              value: bolt://neo4j:7687
            - name: SPRING_NEO4J_AUTHENTICATION_USERNAME
              value: neo4j
            - name: SPRING_NEO4J_AUTHENTICATION_PASSWORD
              value: neo4jpass
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
