apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: amazon
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
              name: redis
          command:
            - redis-server
            - --requirepass
            - redispass
            - --maxmemory
            - 256mb
            - --maxmemory-policy
            - allkeys-lru
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc